name: Check Broken Link

on:
  schedule:
    - cron: 0 0 * * 1
  push:
    paths:
      - '.github/workflows/check-broken-link.yml'

jobs:
  check:
    name: Check Broken Link
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
